### ISSUE TITLE
typo in ReminderClient

### ISSUE THREAD

**Issue by tekutoo** [ask-utils/ask-utils#16]
https://github.com/ask-utils/ask-utils/blob/master/libs/fixtures/reminderClient.js#L112

🤔 RemidnerClient 
🙆 ReminderClient

**Comment by hideokamoto** [comment]
Thanks for the feedback!
But unfortunately, I'll remove the client from the next version.
Because the ASK SDK provides a great service client for the Reminder feature.
https://ask-sdk-for-nodejs.readthedocs.io/en/latest/Calling-Alexa-Service-APIs.html#remindermanagementserviceclient

Please use it instead.

**Comment by tekutoo** [comment]
I think I've learned a lot. 👍
